### ISSUE TITLE
Two results popups appear when using "Find Dependents"

### ISSUE THREAD

**Issue by kaicataldo** [dependents/atom-dependents#20]
The results of "Find Dependents" displays two popups - one empty one and one that displays the correct results. I'll try to take a screenshot later if that would be helpful!

**Comment by kaicataldo** [comment]
Screenshot:
<img width="848" alt="screen shot 2016-06-23 at 12 42 30 am" src="https://cloud.githubusercontent.com/assets/7041728/16292034/72cac8b2-38db-11e6-956e-dc7b6a35c45a.png">

**Comment by mrjoelkemp** [comment]
Thanks! Which atom version is that btw? I wasn't seeing it on the latest atom.

**Comment by kaicataldo** [comment]
Oh, yeah, that would be helpful - I'm on v1.8.0

**Comment by mrjoelkemp** [comment]
Do you see this consistently across different themes? 

I tried theme switching and didn't see the extra popup. Is this related to #19 at all? 

Here's what I'm seeing:

![image](https://cloud.githubusercontent.com/assets/865203/16327066/2b615e54-399a-11e6-8ff3-4ab51bc4bdcf.png)

**Comment by mrjoelkemp** [comment]
Even if I invoke the command back to back (before the first run finishes), I still only see a single file selection window. Any ideas are appreciated.

**Comment by kaicataldo** [comment]
Ah, good call on the theme. I switched to the default One Dark UI Theme and I don't see it. I'll file an issue with the theme I'm using - thanks!

**Comment by mrjoelkemp** [comment]
Woot! Glad to hear it.

Happy to fix anything on my end that might be incorrect.
